### ISSUE TITLE
Dart type errors in checked mode

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/vm_service_drivers#150]
`_call` causes type errors when running the VM in checked mode. E.g. https://github.com/dart-lang/vm_service_drivers/blob/6d40333a63ca63d06fa9c3a38500f3c452499e2e/dart/lib/vm_service_lib.dart#L400.

**Comment by devoncarew** [comment]
Can you include details about the type errors? Thanks!

**Comment by hermanbergwerf** [comment]
In the case I pointed out (the one that fails my program):
```
Unhandled exception:
type '_Future<Response>' is not a subtype of type 'Future<VM>' of 'function result' where
  _Future is from dart:async
  Response is from package:vm_service_lib/vm_service_lib.dart
  Future is from dart:async
  VM is from package:vm_service_lib/vm_service_lib.dart
```

**Comment by hermanbergwerf** [comment]
I don't really understand how that `_call` method is working by the way (VmService is not a generic class with T at Type parameter). Is this an example of a generic method, which is not yet fully implemented in the Dart language? (I see the comment syntax for the analyzer there).

**Comment by devoncarew** [comment]
Yup, this is a generic method - currently using the comment syntax (`/*T*/`).

I don't see these checked modes issues locally; perhaps the code in master is newer than the last published version?

**Comment by devoncarew** [comment]
Speculatively closing as stale -
