### ISSUE TITLE
Optimization: Remove 'accept-encoding: gzip' from default

### ISSUE THREAD

**Issue by joeconwaystk** [dart-lang/vm_service_drivers#165]
We are running into an issue where some heavy duty tests that spawn multiple isolates are failing to run coverage fast enough in Travis-CI (hits the 50 minute maximum). 

Looking at CPU profiler, the coverage tool spends about 15% of runtime decompressing gzipped data (or at least in a method that is only triggered when decompressing data). Since the VM service is most often used intra-machine (?), it might be valuable to turn off gzip by default.

(It doesn't appear that the dart:io Websocket implementation allows this behavior yet.)

**Comment by devoncarew** [comment]
Hi @joeconwaystk, is the coverage tool using this library? This repo is for dart and java libraries to speak the service protocol.

You probably want to file this issue on the dart sdk repo against the vm and debugger implementation?

**Comment by joeconwaystk** [comment]
👍 Got confused on my repos. Will move it there, thanks.
