### ISSUE TITLE
SourceReportKind can't be constructed outside this lib

### ISSUE THREAD

**Issue by dnfield** [dart-lang/vm_service_drivers#210]
I want to call `VmService.getSourceReport`, but I can't provide anything for the list of `SourceReportKind` because its constructor is internal.

It seems like it should offer some static getters or a factory of some sort.

**Comment by devoncarew** [comment]
That looks like a bug in the generator. We use those ~enum classes more for documentation and a way to discover the valid enum values. The param should be taking a String -

```
Future<SourceReport> getSourceReport(
      String isolateId, List<String> reports,
      {String scriptId, int tokenPos, int endTokenPos, bool forceCompile});
```

**Comment by devoncarew** [comment]
Thanks for the report! `3.14.2` is published and should get you unblocked.
