### ISSUE TITLE
Doesn't properly parse `dependencies` for `Library` instances

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/vm_service_drivers#215]
It looks like you just get a null instance for library dependencies today, this can be seen by adding a print for `rootLibrary.dependencies` [here](https://github.com/dart-lang/vm_service_drivers/blob/c0af832a3bd98c945dc78e43f063c6d5d408c29e/dart/example/vm_service_lib_tester.dart#L114).

**Comment by devoncarew** [comment]
It's in the json payload?

We may not handle lists of some objects correctly; we've special cased this in a few places: https://github.com/dart-lang/vm_service_drivers/blob/c0af832a3bd98c945dc78e43f063c6d5d408c29e/dart/tool/dart/generate_dart.dart#L1043

**Comment by jakemac53** [comment]
> It's in the json payload?

Correct, the relevant section of the json payload is:

```
"dependencies":[{"isDeferred":false,"isExport":false,"isImport":true,"prefix":"developer","target":{"type":"@Library","fixedId":true,"id":"libraries\/@4383715","name":"dart.developer","uri":"dart:developer"}}]
```
And this was the result of the parsed `rootLibrary.dependencies`:
```
[null]
```

> We may not handle lists of some objects correctly; we've special cased this in a few places:

Ya I saw we there is some special casing, I haven't tried digging into the actual issue. It isn't a blocker for me in any case I just noticed it in when testing the `toJson` stuff.

**Comment by jakemac53** [comment]
Ah, looking at that payload it doesn't have a `type` field. We can probably hardcode a `createSpecificObject` call to explicitly know it is a `LibraryDependency`?

I wonder if we should always do that if a lot of these objects are missing the type fields? Technically they aren't necessary as you can know from the outer object context what they should be in many cases?

**Comment by jakemac53** [comment]
Confirmed that this can be fixed by adding in this conditional next to the others:

```
      } else if (name == 'Library' && field.name == 'dependencies') {
        // Special case `Library.dependencies`.
        gen.writeln("dependencies = new List<LibraryDependency>.from("
            "_createSpecificObject(json['dependencies'], "
            "LibraryDependency.parse));");
```

**Comment by devoncarew** [comment]
Yeah, when I originally wrote the dart code gen, I'd thought that all the objects coming from the VM would have `type`s. Most of them do, but several (not quite 1st class objects) don't.

We could create a map or something which indicated to us which fields contained objects that don't have types. That way we could preserve much of the current codegen, and the special-casing logic for non-type objects wouldn't be so hand-rolled per instance.

**Comment by jakemac53** [comment]
> Yeah, when I originally wrote the dart code gen, I'd thought that all the objects coming from the VM would have `type`s. Most of them do, but several (not quite 1st class objects) don't.

To be fair, this seems like a bug in the vm implementation of the protocol and these should probably be included. But, it should be reasonable to workaround and does make the payloads a bit smaller.

**Comment by jakemac53** [comment]
ok @devoncarew this is ready for review now

**Comment by jakemac53** [comment]
Fixed by https://github.com/dart-lang/vm_service_drivers/pull/213
