### ISSUE TITLE
tokenPosTable can be null for a Script with no coverable lines

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/vm_service_drivers#230]
The Script.fromJson deserialization doesn't perform a null check however

**Comment by devoncarew** [comment]
https://github.com/dart-lang/vm_service_drivers/blob/master/dart/lib/vm_service_lib.dart#L4125

Yup, looks like it. This will need a change to the generator code.

**Comment by devoncarew** [comment]
The fix was published as `3.15.0`.
