### ISSUE TITLE
getFlagList RPC creates null service objects

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/vm_service_drivers#255]
Calling `getFlagList()` returns a `FlagList` object. `flagList.flags` returns a list of `null`s instead of a list of `Flag`s.

[null, null, ... null, null]

**Comment by bkonyi** [comment]
Looks like the `Flag` object doesn't have a `type` property so it isn't being parsed properly. We'll need to update the vm_service package to not try to create a service object for each element in `FlagList` but just create the `Flag` objects directly using its constructor. I'll make that change once the vm_service package lands in the SDK.

**Comment by bkonyi** [comment]
Fixed [here](https://dart-review.googlesource.com/c/sdk/+/110546).
