### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/vm_service_drivers#257]
Waiting on packages to migrate to https://pub.dev/packages/vm_service

- [x] test_core - https://github.com/dart-lang/test/commit/77e09b4e9aa5e1a3e14191e368b1c7f5536808a5
- [x] coverage - https://github.com/dart-lang/coverage/commit/8aa322fa3faf5a57952a6cd8b3cd8eeb037c1cb3
- [x] devtools - https://github.com/flutter/devtools/commit/1b947895fa033fac11d10af493aa3df5a9562f23
- [x] dwds
- [x] webdev

**Comment by devoncarew** [comment]
for devtools, cc @jacob314 @kenzieschmoll 

for coverage, cc @cbracken @grouma

**Comment by grouma** [comment]
Is the replacement ready?

**Comment by devoncarew** [comment]
> Is the replacement ready?

cc @bkonyi

**Comment by bkonyi** [comment]
@grouma, the replacement is `package:vm_service` ([here on pub](https://pub.dev/packages/vm_service)).

**Comment by kevmoo** [comment]
Closing this out! Going to archive.

CC @mit-mit
