### ISSUE TITLE
when generating, update the pubspec version to match the protocol

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/vm_service_drivers#28]
We should update the pubspec to reflect the version of the protocol. Perhaps inject the major and minor version into the pubspec version, and keep the patch number (and build metadata) as is?

**Comment by danrubel** [comment]
Do we want to support multiple versions of the protocol ? Perhaps generate libraries which include the version # in the library name and file name? E.g. vm_service_lib_2.dart contains library vm_service_lib_2 ?

**Comment by devoncarew** [comment]
Let's discuss. I'm not clear of the best way forward. It seems like the two problems are tools not being able to talk to n - 1 VMs (slightly older VMs), and when a new VM comes out (n + 1 protocol), none of the existing tools can talk to it.

**Comment by danrubel** [comment]
Yes, not sure how to proceed on this. If we have access to the n+1 spec, we can do what we can to support protocol version n+1 in the version n codebase. That might be the right approach to give tools the longest support runway for any given version of this client.

**Comment by devoncarew** [comment]
Yeah, but I'm afraid we might not know about n+1 when we ship :)
