### ISSUE TITLE
open an issue or PR re: the spec fix for `BoundField[] fields [optional]`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/vm_service_drivers#57]
https://github.com/dart-lang/vm_service_drivers/pull/55/files#diff-68936077052390239c77a3732f47e9ccR1365

**Comment by devoncarew** [comment]
@danrubel, done?

**Comment by danrubel** [comment]
https://github.com/dart-lang/sdk/pull/24481 ... still waiting

**Comment by danrubel** [comment]
Fixed!
