### ISSUE TITLE
Bad return value

### ISSUE THREAD

**Issue by danrubel** [dart-lang/vm_service_drivers#65]
Incorrectly [returning null](https://github.com/dart-lang/vm_service_drivers/blob/master/java/src/org/dartlang/vm/service/element/Element.java#L44)

**Comment by alexander-doroshko** [comment]
![image](https://cloud.githubusercontent.com/assets/4499789/10372959/40e36ed4-6df3-11e5-9eb7-41ad7cbc9528.png)

**Comment by alexander-doroshko** [comment]
@danrubel We need to keep code Java 1.6 compatible, can you please avoid `new ArrayList<>` constructs?

**Comment by danrubel** [comment]
Ah! Did not know that. https://github.com/dart-lang/vm_service_drivers/issues/73
