### ISSUE TITLE
Java client incorrectly forwards of instance references

### ISSUE THREAD

**Issue by danrubel** [dart-lang/vm_service_drivers#67]
See VmService.forwardResponse(). It has 6 places where it checks responseType equality to "FooRef". But VM never sends "type":"FooRef", it sends "type":"@Foo" instead. As a result VmService.forwardResponse() falls back to logUnknownResponse().

**Comment by devoncarew** [comment]
I think `@Foo` is their way of saying `FooRef`. It may be that the translation code needs to handle the `@` refs?

**Comment by danrubel** [comment]
Exactly. Incorrect code gen.

**Comment by alexander-doroshko** [comment]
![image](https://cloud.githubusercontent.com/assets/4499789/10372898/ed7a3368-6df2-11e5-889e-ab00b6b2c161.png)

**Comment by danrubel** [comment]
Thanks!
