### ISSUE TITLE
Build failing on Travis

### ISSUE THREAD

**Issue by sethladd** [dart-lang/vm_service_drivers#87]
Just FYI

**Comment by sethladd** [comment]
cc @danrubel @devoncarew

**Comment by devoncarew** [comment]
This java integration test is flaky (https://travis-ci.org/dart-lang/vm_service_drivers/jobs/85128480#L243); we've tried to address it in the past. The PR passed dev and stable, but the merge to master failed (stable, but not dev).

**Comment by devoncarew** [comment]
Some 'unexpected events' in this one: https://travis-ci.org/dart-lang/vm_service_drivers/jobs/85177761

**Comment by devoncarew** [comment]
One thing I just figured out - when the dart part of the build fails, the java part still runs. That java build says 'build successful; exit 0'; the (actual) dart failure is listed much further up the travis results page.

**Comment by devoncarew** [comment]
fixed?
