### ISSUE TITLE
rev java library to match the latest protocol spec

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/vm_service_drivers#93]
For details, see https://github.com/dart-lang/vm_service_drivers/pull/91.

@danrubel

**Comment by devoncarew** [comment]
(Java travis commented out in https://github.com/dart-lang/vm_service_drivers/pull/95/files#diff-354f30a63fb0907d4ad57269548329e3R9)

**Comment by devoncarew** [comment]
Re: optional params into the Java methods, instead of using primitive types for those params, you can type them as objects (i.e., `Integer` instead of `int`). That would be a way to know if the user had actually passed them in, and they should be adding to the json packet.

**Comment by danrubel** [comment]
Good point. I'll work towards that.

**Comment by danrubel** [comment]
https://github.com/dart-lang/vm_service_drivers/pull/104

**Comment by devoncarew** [comment]
fixed
